-- Statement 1:
SELECT * FROM EMPLOYEE WHERE EMPLOYEE_NAME='Nurul';

-- Statement 2:
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE FROM PRODUCT;

-- Statement 3:
SELECT PRODUCT_NAME FROM PRODUCT WHERE CATEGORY = 'fruit';

-- Statement 4:
DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID='4';

-- Statement 5:
SELECT RECEIPT_ID, RECEIPT_DATETIME FROM RECEIPT WHERE RECEIPT_DATETIME >= TO_TIMESTAMP('23-08-2022 00:00:00', 'DD-MM-YYYY HH24:MI:SS') AND  RECEIPT_DATETIME <= TO_TIMESTAMP('25-08-2022 23:59:59', 'DD-MM-YYYY HH24:MI:SS');

-- Statement 6:
SELECT EMPLOYEE.EMPLOYEE_ID, EMPLOYEE.EMPLOYEE_NAME, WORK_TIME.WORKING_DATE FROM EMPLOYEE INNER JOIN WORK_TIME ON EMPLOYEE.EMPLOYEE_ID = WORK_TIME.EMPLOYEE_ID;

-- Statement 7:
SELECT * FROM MEMBERSHIP;
INSERT INTO MEMBERSHIP VALUES ('61','Julius', 'female', 'No 6,Jalan Pelangi, Taman Pelangi, 40000Klang, Selangor', 'standard');

-- Statement 8:
SELECT SALES_DATE, SUM(TOTAL_SALES) AS TOTAL_SALES_IN_A_DAY FROM SALES WHERE SALES_DATE='23/08/2022' GROUP BY SALES_DATE;

-- Statement 9:
SELECT PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_NAME, PRODUCT.PRODUCT_PRICE, PROMOTION.PROMOTION_PRICE, (PRODUCT.PRODUCT_PRICE - PROMOTION.PROMOTION_PRICE) AS DISCOUNT FROM PRODUCT INNER JOIN PROMOTION ON PRODUCT.PROMOTION_ID = PROMOTION.PROMOTION_ID;

-- Statement 10:
UPDATE PRODUCT SET PRODUCT_PRICE = 11.2 WHERE PRODUCT_ID = '1780'; 

-- Statement 11:
SELECT PAYMENT.TRANSACTION_NO, MEMBERSHIP.MEMBER_NAME, PAYMENT.PAYMENT_METHOD FROM RECEIPT INNER JOIN PAYMENT ON RECEIPT.PAYMENT_ID = PAYMENT.PAYMENT_ID INNER JOIN MEMBERSHIP ON RECEIPT.MEMBER_ID = MEMBERSHIP.MEMBER_ID WHERE PAYMENT.PAYMENT_METHOD = 'cash';

-- Statement 12:
SELECT RECEIPT.RECEIPT_ID, RECEIPT.TOTAL_PRICE, (RECEIPT.TOTAL_PRICE * (100-MEMBER_TYPE.MEMBER_DISCOUNT_RATE)/100) AS Actual_Amount_Paid, (RECEIPT.TOTAL_PRICE * (MEMBER_TYPE.MEMBER_DISCOUNT_RATE)/100) AS Discount_Amount FROM MEMBERSHIP INNER JOIN RECEIPT ON MEMBERSHIP.MEMBER_ID = RECEIPT.MEMBER_ID INNER JOIN MEMBER_TYPE ON MEMBER_TYPE.MEMBER_TYPE = MEMBERSHIP.MEMBER_TYPE;

